# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

requiredVersions:
    azd: '>=1.14.0'
name: voice-live-agent
metadata:
    template: voice-live-agent@0.1.0
services:
    TripPlannerAgent:
        project: src/travel_agency/TripPlannerAgent
        host: azure.ai.agent
        language: python
        config:
            container:
                resources:
                    cpu: "0.5"
                    memory: 1Gi
    app:
        project: server
        host: containerapp
        language: python
        docker:
            path: Dockerfile
            remoteBuild: true
pipeline:
    provider: ""
    variables:
        - AZURE_LOCATION
        - AZURE_RESOURCE_GROUP
        - AZURE_CONTAINER_REGISTRY_ENDPOINT
        - SERVICE_API_ENDPOINTS
        - AZURE_VOICE_LIVE_ENDPOINT
    secrets: []
