FROM python:3.12-slim

WORKDIR /app

COPY . vita_agent/
WORKDIR /app/vita_agent

RUN if [ -f requirements.txt ]; then \
        pip install -r requirements.txt; \
    else \
        echo "No requirements.txt found"; \
    fi

EXPOSE 8088

CMD ["python", "main.py"]
